
name: Tailscale VPN

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:ci

      - name: Check Tailscale
        run: |
          echo "=== Tailscale status ==="
          tailscale status

          echo
          echo "=== Tailscale IP ==="
          tailscale ip
